### URL for problems: https://www.w3resource.com/python-exercises/numpy/basic/index.php

In [1]:
import numpy as np

##### 24. Write a NumPy program to multiply the values of two given vectors.

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(f'{a * 2}\n{b * 2}')

[2 4 6]
[ 8 10 12]


##### 25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [10]:
a = np.array([[i+n for n in range(4)] for i in range(10, 22, 4)])
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

##### 26. Write a NumPy program to find the number of rows and columns of a given matrix.

In [12]:
# Using the previous vector:
rnc = a.shape
print(f'Rows: {rnc[0]}, columns: {rnc[1]}')

Rows: 3, columns: 4
