### URL for problems: https://www.w3resource.com/python-exercises/numpy/basic/index.php

In [1]:
import numpy as np

##### 34. Write a NumPy program to add a vector to each row of a given matrix.

In [19]:
a = np.array([[np.random.randint(0, 10) for i in range(3)] for i in range(3)])
v = np.array([np.random.randint(0, 10) for i in range(3)])
print(f'Original matrix:\n{a}')
print(f'Vector to add to each row:\n{v}')
c = np.empty_like(a)
for i in range(3):
    c[i, :] = a[i, :] + v
print(f'New matrix:\n{c}')

Original matrix:
[[3 5 3]
 [1 8 0]
 [2 2 4]]
Vector to add to each row:
[3 8 5]
New matrix:
[[ 6 13  8]
 [ 4 16  5]
 [ 5 10  9]]


##### 39. Write a NumPy program to convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not.

In [24]:
a = [[x, x * np.random.randint(1, 5), (x + np.random.randint(1, 5)) / np.random.randint(1, 3)] for x in range(1, 4)]
a_array = np.array(a)
b = a_array.tolist()
a == b

True